# Ruff Configuration.
# ==================

line-length = 88
target-version = "py311"

[format]

[lint]
select = [
    "F",    # Pyflakes.
    "E",    # pycodestyle error.
    "W",    # pycodestyle warning.
    "C90",  # mccabe.
    "I001", # isort.
    "N",    # pep8 naming.
    "D",    # pydocstyle.
    "UP",   # pyupgrade.
    "ANN",  # flake8-annotations.
    "S",    # flake8-bandit.
    "B",    # flake8-bugbear.
    "C4",   # flake8-comprehensions.
    "SIM",  # flake8-simplify.
    "TID",  # flake8-tidy-imports.
    "Q",    # flake8-quotes.
    "PT",   # flake8-pytest-style.
]
ignore = []

[lint.pydocstyle]
convention = "pep257"

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-quotes]
inline-quotes = "double"
docstring-quotes = "double"
multiline-quotes = "double"

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"**/test_*" = ["S101"]
"**/schemas.py" = ["N801", "D106"]
